# Generated by Django 6.0.6 on 2026-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1', models.CharField(max_length=100)),
                ('drug2', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=20)),
                ('risk', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
