# Generated by Django 6.0.6 on 2026-06-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('alternative_name', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
