# Generated by Django 6.0.6 on 2026-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_drugalternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drugalternative',
            name='suggested_dosage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
