# Generated by Django 6.0.6 on 2026-06-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_drug_category_drugalternative_suggested_dosage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugalternative',
            name='suggested_dosage',
        ),
    ]
