# Generated by Django 6.0.6 on 2026-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_remove_drugalternative_suggested_dosage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100, unique=True)),
                ('side_effects', models.TextField(blank=True)),
                ('pregnancy_warning', models.TextField(blank=True)),
                ('pediatric_warning', models.TextField(blank=True)),
                ('max_daily_dosage', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
