# Generated by Django 6.0.6 on 2026-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondrug',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
