# Generated by Django 6.0.6 on 2026-06-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescriptiondrug_follow_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='prescriptiondrug',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptiondrug',
            name='drug_name',
        ),
        migrations.RemoveField(
            model_name='prescriptiondrug',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescriptiondrug',
            name='follow_up_date',
        ),
    ]
