# Generated by Django 6.0.6 on 2026-06-18 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(default='Unknown Doctor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='dosage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='drug_name',
            field=models.CharField(default='Unknown Drug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptiondrug',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
